### ISSUE TITLE
Proposition plateforme alternative de mise en relation

### ISSUE THREAD

**Issue by yann-yinn** [etnbrd/awesome-freelance-fr#21]
Bonjour ! 
Merci pour ce repo qui contient plein de liens bien utiles !

Je vous soumets l'existence d'une plateforme de mise en relation open-source et (vraiment) gratuite et décentralisée qui s'appelle "Popcorn" (dont je suis l'auteur):  Elle est auto-gérée par les développeurs dans chaque localité / ville qui souhaite en lancer un.  Voici par exemple le Popcorn de Nantes : 

https://popcorn-nantes.github.io/

La plateforme vient tout juste de se lancer à Rennes ( https://popcorn-rennes.github.io/) et dans le Morbihan (https://popcorn-morbihan.github.io/)

**Comment by etnbrd** [comment]
Hello Yann,

D'abord, désolé pour ma réactivité d’huître morte. Je suis en road trip au fin fond de l'Australie, avec une très mauvaise connexion internet, et pas suffisamment de temps pour lire mes mails à une fréquence respectable.

Merci à toi pour cette plateforme, que je connaissais pas, et qui semble très inintéressante et prometteuse.
Un développeur à déjà listé celle du Morbihan (https://github.com/nicolaslechenic).

Libre à toi de soumettre des PR sur ce dépôt pour que j'ajoute les liens que tu souhaite.
Je les accepterais aussi vite que possible, ou à mon retour à la civilisation, d'ici 3 semaines environ.

Par ailleurs, je serais potentiellement intéressé pour m'occuper de m'occuper des plateformes de Paris et/où Lyon. Et pourquoi pas aider au développement de la plateforme, également.
Tu aurais un lien vers le dépôt ?
edit : je viens de trouver le lien : https://github.com/popcorn-nantes/popcorn-nantes

Merci,

Cheers,

Etienne.

**Comment by yann-yinn** [comment]
Salut ! Road trip en Australie, en voilà une bonne idée ! c'est noté pour le PR
Le code open source du code métier qui génère les Popcorns est plutôt ici pour info : https://github.com/popcorn-nantes/popcorn-machine , au plaisir de rediscuter de tout ça à ton retour, et bien sur ok pour Paris ou Lyon :)
