### ISSUE TITLE
Lien mort Calculateur de charges EURL / SASU et source obsolète

### ISSUE THREAD

**Issue by tomsihap** [etnbrd/awesome-freelance-fr#37]
- Le lien `Calculateur de charges EURL / SASU (free) (source)` est mort. http://antoineviau.com/eurl-sasu/
- La source pointe vers un projet n'ayant des calculs que pour 2017 et 2018 (outdaté) https://github.com/AntoineViau/eurl-sasu

**Comment by etnbrd** [comment]
Ok, merci :)
