### ISSUE TITLE
suggestion Mutuelle / Retraite

### ISSUE THREAD

**Issue by AmauryVanEspen** [etnbrd/awesome-freelance-fr#67]
Bonjour,
je voudrais vous suggérer ce site pour l'adhésion obligatoire Mutuelle et Retraite,
excellent retour et mise en place : http://www.magalix.fr/
Cordialement
Amaury

**Comment by etnbrd** [comment]
Hello 👋 
Pas de souci, est-ce que je peux te laisser ouvrir une Pull Request ?
Merci !
